services:
  nest_app_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - nest_app_db_data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'

volumes:
  nest_app_db_data:
